KsiegarniaPKP/Controllers/DostawasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KsiegarniaPKP.Models;

namespace KsiegarniaPKP.Controllers
{
    public class DostawasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DostawasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Dostawas
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Dostawy.Include(d => d.Kurier).Include(d => d.Pracownik);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Dostawas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dostawa = await _context.Dostawy
                .Include(d => d.Kurier)
                .Include(d => d.Pracownik)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dostawa == null)
            {
                return NotFound();
            }

            return View(dostawa);
        }

        // GET: Dostawas/Create
        public IActionResult Create()
        {
            ViewData["KurierId"] = new SelectList(_context.Uzytkownik, "Id", "Id");
            ViewData["PracownikId"] = new SelectList(_context.Uzytkownik, "Id", "Id");
            return View();
        }

        // POST: Dostawas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PracownikId,KurierId,Adres,Status,CzyOplacone")] Dostawa dostawa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dostawa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["KurierId"] = new SelectList(_context.Uzytkownik, "Id", "Id", dostawa.KurierId);
            ViewData["PracownikId"] = new SelectList(_context.Uzytkownik, "Id", "Id", dostawa.PracownikId);
            return View(dostawa);
        }

        // GET: Dostawas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dostawa = await _context.Dostawy.FindAsync(id);
            if (dostawa == null)
            {
                return NotFound();
            }
            ViewData["KurierId"] = new SelectList(_context.Uzytkownik, "Id", "Id", dostawa.KurierId);
            ViewData["PracownikId"] = new SelectList(_context.Uzytkownik, "Id", "Id", dostawa.PracownikId);
            return View(dostawa);
        }

        // POST: Dostawas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PracownikId,KurierId,Adres,Status,CzyOplacone")] Dostawa dostawa)
        {
            if (id != dostawa.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dostawa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DostawaExists(dostawa.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["KurierId"] = new SelectList(_context.Uzytkownik, "Id", "Id", dostawa.KurierId);
            ViewData["PracownikId"] = new SelectList(_context.Uzytkownik, "Id", "Id", dostawa.PracownikId);
            return View(dostawa);
        }

        // GET: Dostawas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dostawa = await _context.Dostawy
                .Include(d => d.Kurier)
                .Include(d => d.Pracownik)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dostawa == null)
            {
                return NotFound();
            }

            return View(dostawa);
        }

        // POST: Dostawas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dostawa = await _context.Dostawy.FindAsync(id);
            _context.Dostawy.Remove(dostawa);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DostawaExists(int id)
        {
            return _context.Dostawy.Any(e => e.Id == id);
        }
    }
}

KsiegarniaPKP/Controllers/KoszykController.cs
using KsiegarniaPKP.Models;
using KsiegarniaPKP.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace KsiegarniaPKP.Controllers
{
    [Authorize(Roles = "Uzytkownik")]
    public class KoszykController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _hostingEnviroment;
        private UserManager<Uzytkownik> _userManager;
        public KoszykController(ApplicationDbContext context, IHostingEnvironment hostingEnviroment, UserManager<Uzytkownik> userManager)
        {
            _context = context;
            _hostingEnviroment = hostingEnviroment;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            string userId = _userManager.GetUserId(User);
            float sumarycznie = 0f;

            var pozycjeKoszyka = await _context.PozycjaKoszyka
                .Where(pk => pk.KlientId == userId)
                .Include(pk => pk.Oferta)
                .ThenInclude(o => o.Ksiazka)
                .ToListAsync();

            var koszyk = pozycjeKoszyka
                .GroupBy(pk => pk.Oferta.Ksiazka)
                .Select(group => new PozycjaKoszykaViewModel
                {
                    Ksiazka = group.Key,
                    Ilosc = group.Count(),
                    Sumarycznie = group.Key.Cena * group.Count()
                }).ToList();

            foreach(var pk in koszyk)
            {
                sumarycznie += pk.Sumarycznie;
            }

            ViewBag.sumarycznie = sumarycznie;

            return View(koszyk);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult IncrementCartItem(int ksiazkaId)
        {
            string userId = _userManager.GetUserId(User);

            var oferta = _context.Oferty
                                 .FirstOrDefault(o => o.Dostepnosc && o.KsiazkaId == ksiazkaId);

            if (oferta == null)
            {
                TempData["brakOferty"] = true;
                return RedirectToAction("Index");
            }

            oferta.Dostepnosc = false;

            var pozycjaKoszyka = new PozycjaKoszyka
            {
                KlientId = userId,
                OfertaId = oferta.OfertaId
            };
            _context.PozycjaKoszyka.Add(pozycjaKoszyka);
            try
            {
                _context.SaveChanges();
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Błąd podczas zapisu do bazy danych");
            }

            return RedirectToAction("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DecrementCartItem(int ksiazkaId)
        {
            string userId = _userManager.GetUserId(User);

            var pozycjaKoszyka = _context.PozycjaKoszyka
                                         .Include(pk => pk.Oferta)
                                         .FirstOrDefault(pk => pk.KlientId == userId && pk.Oferta.KsiazkaId == ksiazkaId);

            if (pozycjaKoszyka == null)
            {
                return NotFound();
            }

            _context.PozycjaKoszyka.Remove(pozycjaKoszyka);

            var oferta = _context.Oferty
                                 .FirstOrDefault(o => o.OfertaId == pozycjaKoszyka.OfertaId);

            if (oferta != null)
            {
                oferta.Dostepnosc = true;
            }

            try
            {
                _context.SaveChanges();
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Błąd podczas zapisu do bazy danych");
            }

            return RedirectToAction("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveCartItem(int ksiazkaId)
        {
            var pozycjeKoszyka = _context.PozycjaKoszyka
                                         .Include(pk => pk.Oferta)
                                         .Where(pk => pk.Oferta.KsiazkaId == ksiazkaId)
                                         .ToList();

            if (!pozycjeKoszyka.Any())
            {
                return NotFound();
            }

            _context.PozycjaKoszyka.RemoveRange(pozycjeKoszyka);

            var ofertaIds = pozycjeKoszyka.Select(pk => pk.OfertaId).Distinct();
            var oferty = _context.Oferty
                                 .Where(o => ofertaIds.Contains(o.OfertaId))
                                 .ToList();

            foreach (var oferta in oferty)
            {
                oferta.Dostepnosc = true;
            }

            try
            {
                _context.SaveChanges();
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Błąd podczas zapisu do bazy danych");
            }

            return RedirectToAction("Index");
        }


    }
}

KsiegarniaPKP/Controllers/OfertasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KsiegarniaPKP.Models;

namespace KsiegarniaPKP.Controllers
{
    public class OfertasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OfertasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Ofertas
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Oferty.Include(o => o.Ksiazka);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Ofertas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oferta = await _context.Oferty
                .Include(o => o.Ksiazka)
                .FirstOrDefaultAsync(m => m.OfertaId == id);
            if (oferta == null)
            {
                return NotFound();
            }

            return View(oferta);
        }

        // GET: Ofertas/Create
        public IActionResult Create()
        {
            ViewData["KsiazkaId"] = new SelectList(_context.Ksiazki, "Id", "Autor");
            return View();
        }

        // POST: Ofertas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OfertaId,KsiazkaId,Dostepnosc")] Oferta oferta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(oferta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["KsiazkaId"] = new SelectList(_context.Ksiazki, "Id", "Autor", oferta.KsiazkaId);
            return View(oferta);
        }

        // GET: Ofertas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oferta = await _context.Oferty.FindAsync(id);
            if (oferta == null)
            {
                return NotFound();
            }
            ViewData["KsiazkaId"] = new SelectList(_context.Ksiazki, "Id", "Autor", oferta.KsiazkaId);
            return View(oferta);
        }

        // POST: Ofertas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OfertaId,KsiazkaId,Dostepnosc")] Oferta oferta)
        {
            if (id != oferta.OfertaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(oferta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OfertaExists(oferta.OfertaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["KsiazkaId"] = new SelectList(_context.Ksiazki, "Id", "Autor", oferta.KsiazkaId);
            return View(oferta);
        }

        // GET: Ofertas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oferta = await _context.Oferty
                .Include(o => o.Ksiazka)
                .FirstOrDefaultAsync(m => m.OfertaId == id);
            if (oferta == null)
            {
                return NotFound();
            }

            return View(oferta);
        }

        // POST: Ofertas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var oferta = await _context.Oferty.FindAsync(id);
            _context.Oferty.Remove(oferta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OfertaExists(int id)
        {
            return _context.Oferty.Any(e => e.OfertaId == id);
        }
    }
}

KsiegarniaPKP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ksiegarnia PKP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        .centered {
            position: fixed; /* Ustawia element w sposób stały na ekranie */
            top: 25%; /* Ustawia górny margines na 50% wysokości okna */
            left: 50%; /* Ustawia lewy margines na 50% szerokości okna */
            transform: translate(-50%, -50%); /* Przesuwa element o 50% jego szerokości i wysokości w lewo i w górę */
            text-align: center; /* Centruje tekst w poziomie */
        }
    </style>
    <style>
        table td, th {
            text-align: center !important;
            vertical-align: middle !important;
        }
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ksiegarnia PKP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" style="display: flex; align-items: center;">
                            <a asp-controller="Home" asp-action="Index" style="display: flex; align-items: center; margin-right: 10px;">
                                <img src="~/image/home.png" width="30" height="30" alt="Cart" />
                            </a>
                        </li>
                        @if (User.IsInRole("Uzytkownik"))
                        {
                            <li class="nav-item" style="display: flex; align-items: center;">
                                <a asp-controller="Koszyk" asp-action="Index" style="display: flex; align-items: center;">
                                    <img src="~/image/cart.png" width="30" height="30" alt="Cart" />
                                </a>
                            </li>
                        }
                        @if (User.IsInRole("Admin") || User.IsInRole("Pracownik") || User.IsInRole("Uzytkownik"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dokuments" asp-action="Index">Dokumenty</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dostawas" asp-action="Index">Dostawy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Ksiazkas" asp-action="Index">Książki</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Ofertas" asp-action="Index">Oferty</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PozycjaKoszykas" asp-action="Index">Pozycje koszyków</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Zamowienies" asp-action="Index">Zamówienia</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Ksiegarnia PKP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Polityka</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>